### ISSUE TITLE
Debugger call in main.coffee

### ISSUE THREAD

**Issue by tmunro** [viddo/recent-files-fuzzy-finder#10]
Hi,

It looks like there's a call to `debugger` on https://github.com/viddo/recent-files-fuzzy-finder/blob/master/lib/main.coffee#L24

Could you remove that? It triggers when I'm in dev mode :cry:

**Comment by viddo** [comment]
Oh my, that's embarrassing :scream: 
Fixed in #9 by @forivall (big thx!), released in v0.2.1

**Comment by forivall** [comment]
Out of habit, I (almost) always use `git add -p` so I can do a quick self-code review. It might be useful :wink:
