### ISSUE TITLE
Sort files by most-recently-opened

### ISSUE THREAD

**Issue by alexweber** [viddo/recent-files-fuzzy-finder#15]
This package is great, thanks!  Would be awesome if there was an option or default setting to display the files sorted by the most recently opened ones.

**Comment by alexweber** [comment]
Oops, nevermind... I could have sworn this wasn't working a couple weeks ago but seems to be fine now... :+1:

**Comment by viddo** [comment]
They should be sorted like that, but perhaps maybe you experienced the same issue I described in https://github.com/viddo/recent-files-fuzzy-finder/issues/8#issuecomment-162105731? It was released a few days back.

I'm happy that you find the package useful BTW. :)

**Comment by alexweber** [comment]
@viddo Good call, that looks like it could have been it!

Dude, i love this package, this was one of the things I missed the most about Jetbrains IDEs... :+1: Thanks! :)
