### ISSUE TITLE
Remember last cursor position

### ISSUE THREAD

**Issue by pvorona** [viddo/recent-files-fuzzy-finder#17]
Is it possible to open recent files with cursor placed at its' last position it this file?

**Comment by viddo** [comment]
Technically, yes, most definitely. But I consider that to be a package of its own. For fun trivia, that's what I implemented in https://github.com/viddo/Eclipse-plugin-Restore-file-position for the [Eclipse](http://www.eclipse.org/) IDE a few years back.

Luckily, someone else [already solved it (see `remember-file-positions` package)](https://atom.io/packages/remember-file-positions)!

Thanks for reminding me of that feature. :)
