### ISSUE TITLE
only max of 10 recent files ever displayed

### ISSUE THREAD

**Issue by andrew-james-heard** [viddo/recent-files-fuzzy-finder#28]
The default is 50. I tried increasing this to 100 & then noticed there were only 10 in the list. I can't confirm whether I ever saw more than 10 in the list before I changed this setting. Changed it back to 50, still only 10 in the list. To reproduce I simply found a folder that had lots of text files, main menu > File Open > select all files, open the recent files panel, always count only 10 recent files. Close atom, reopen, same 10 in list.

**Comment by viddo** [comment]
The setting is for the amount of closed files to _remember_, not to define the amount of visible items in the view. That limit is unfortunately a hardcoded restriction in the internals of [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder) which view this package extends/builds upon.

I'm not aware of any public API/setting to change the amount of visible items in the view, or have had any issues with this limitation. If you can find a way to modify it that doesn't involved reaching into undocumented internals I'm open for a PR.

**Comment by viddo** [comment]
To clarify my opinion: I'm not aware of any public API/setting at least, or have had any issues with this limitation. If you can find a way to modify it that doesn't involved reaching into undocumented internals I'm open for a PR.

**Comment by andrew-james-heard** [comment]
Ah OK. My misunderstanding, and thanks for clarifying. Although from a users point of view not sure why there would be a setting "Max Files To Remember" and not display all those files in the list. Maybe performance reasons.
