### ISSUE TITLE
Sort by recently opened, but then show all files?

### ISSUE THREAD

**Issue by max-sixty** [viddo/recent-files-fuzzy-finder#29]
With Atom's default fuzzy finder, I frequently find myself having to navigate with the arrow keys to the same file repeatedly. So this package has the potential to solve that problem. 

But I'm also not _sure_ whether I've recently opened the file and, in the case that I haven't, I then need to exit this finder and use the standard fuzzy finder, retyping the same file name again.

How would you feel about combining the approaches - having this finder _first_ list the recently opened files, but if there's no match, then default to the traditional fuzzy finder list?

**Comment by viddo** [comment]
Personally I'd find it confusing to get different results depending on what I type in. 

I see what you're aiming for though, but I think it should be solved in a different, more explicit way. e.g. hitting the defualt fuzzy-finder keyboard shortcut while this package's view being open, to switch over to the default fuzzy-finder with the same search terms filled in.

**Comment by max-sixty** [comment]
> e.g. hitting the defualt fuzzy-finder keyboard shortcut while this package's view being open, to switch over to the default fuzzy-finder with the same search terms filled in.

Yes that's a good idea
