### ISSUE TITLE
Finder missing entries in New Window

### ISSUE THREAD

**Issue by robert-newton** [viddo/recent-files-fuzzy-finder#35]
1) Open a project in an atom window and open a number of files in a single frame.
  - Note that the recent files fuzzy finder works correctly, allowing it to be used to
    switch between all open tabs.
2) Use the File menu to open a new window.
3) From the File menu in the new window, use Add Project Folder to add the directory associated
    with the project opened in the original window.
  - Note that atom automatically opens all the files/tabs in the new window that are currently
    open in the original window.
  - Note that the default fuzzy-finder:toggle-buffer-finder will list all the currently open
    files/tabs in the new window
  - If open-recent is installed, note that it will correctly list the recent files from the File
    menu of the new window.
4) Activate recent-files-fuzzy-finder:toggle-finder
  - Note that it does not correctly list even the current files/tabs in the New Window

**Comment by viddo** [comment]
Hmm, never used the "new window" feature myself but I'd guess it might be the activate method not being triggered or something like that. Feel free to do a PR if you figure out a fix. :)
