### ISSUE TITLE
Persists the list of recent files closed

### ISSUE THREAD

**Issue by kenng** [viddo/recent-files-fuzzy-finder#6]
Thanks for creating the plugin!

Currently the list will be cleared once atom is closed. Is there any way to persist it so that the list can be used during next atom launch? That would be useful!

**Comment by viddo** [comment]
Yeah sure, had not implemented it until now since had not really needed it. Done :point_right:  #7 (will release promptly)

**Comment by viddo** [comment]
released in 0.2.0
