### ISSUE TITLE
List of files is not in most recently used order

### ISSUE THREAD

**Issue by tmunro** [viddo/recent-files-fuzzy-finder#8]
Not sure why this is happening - I'll update if I can figure it out - but my list of files is not in the order that I closed or left them. It seems to change unpredictably - if I go to the top entry in the list and close that, I'll have a new, different top entry that also isn't a recent file.

Update: clearing the most recently used file list and re-opening it fixed the issue for me, for now.

**Comment by viddo** [comment]
Thanks for the report! If you can reproduce some scenario consistently let me know, I'll keep an eye out too for what you described here.

**Comment by tmunro** [comment]
I think it may have to do with changing branches that remove the files currently open in Atom. That's my best guess so far.

**Comment by viddo** [comment]
I discovered a bug (886464d45b98b30073e94b0181b97abf07c69867) while working on another one tonight, that might explain what you experienced, although I'm not sure that was your scenario as I experienced (restarting Atom screwed up a counter used to sort the last opened file)? Fix was released in v0.2.4.

**Comment by tmunro** [comment]
Great! I'll test it out when I get a chance, but I'll close this for now.
